name: Hello GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello
        run: echo "Hello Viresh, GitHub Actions is working!"

      - name: Show repository
        run: echo "My static website is running through GitHub Actions."